### PR TITLE
1.12 server for eagler x

### PR DESCRIPTION
**Pull request by STPv22**
I'm not completely sure if this works.

### CODE REVIEW

**Comment by wxnnvs** [comment]
You've gotta add ProtocolSupport or ViaBackwards for 1.12 to work

**Comment by STPv22** [comment]
Alr, I'll check it out.

**Comment by STPv22** [comment]
Do I have to specifically get protocol support for 1.12 or Should I get another version?

**Comment by STPv22** [comment]
Ok, I ca

**Comment by STPv22** [comment]
I accidentally closed.

**Comment by wxnnvs** [comment]
Np

**Comment by wxnnvs** [comment]
I've got some problems with git at the moment
I will merge after my own pullrequests are fixed
Nice work tho

**Comment by STPv22** [comment]
Thx, facing I know nothing about python, I think so too.

**Comment by STPv22** [comment]
unrelated, but how's the cpanel going?

**Comment by wxnnvs** [comment]
im deleting it, but there is gonna be a web panel when full docker support releases

**Comment by STPv22** [comment]
ok, cool

**Pull request closed without merging**
