### PR TITLE
Refactor to Docker container and add webserver to start & stop

### LINKED ISSUE #7: Support for Macos
Could AutoEagler run on Macos? The batch script may need to be expanded to add support for bash.

### PR DESCRIPTION
**Pull request by thgh**
Resolve #7

### CODE REVIEW

**Comment by wxnnvs** [comment]
Nice
Fixt dit ook alle configuratie files of moet ik dat nog doen?

**Comment by thgh** [comment]
Which configuration files?

You can try like this:
```
docker run --rm -it -e PORT=24025 -p 24025:24025 thgh/autoeagler-webserver
```
It downloads the jar files when needed and creates folders to keep it clean.

Screenshot 2024-02-18 at 00 24 26

**Comment by wxnnvs** [comment]
Bungee and spigot need to be ran 1 time (after enabling eula) to generate all files
This includes files where you can link bungee and spigot and fix the eaglercraft support

I will take a look at it next week
(Look in autoeagler.py for the setup part for reference)

**Comment by thgh** [comment]
This?

https://github.com/wxnnvs/AutoEagler/blob/00e41d11fcd3f19dfe956639926881303edc633c/autoeagler.py#L345-L349

Seems doable, it could be handled at the moment the server has started: 

https://github.com/wxnnvs/AutoEagler/blob/8e8dd28da6e7166d568aa7a26987cc5f71d2ed67/docker/server.ts#L253-L254

Does the server need to be restarted after applying the config changes? That can also be automated.

**Comment by wxnnvs** [comment]
Yeah, exactly (+ all the other "replace_in_file()'s")

**Comment by wxnnvs** [comment]
im gonna pull and modify where necessary

**Comment by thgh** [comment]
Feel free to create a branch and new PR and I will review :-)

**Pull request merged**
